### ISSUE TITLE
Unable to merge dex

### ISSUE THREAD

**Issue by rranjanjanacare** [Appolica/Flubber#12]
My gradle file is as below

> apply plugin: 'com.android.application'
>
> apply plugin: 'kotlin-android'
>
>apply plugin: 'kotlin-android-extensions'
>
>repositories {
>   maven {
>        url "https://repo.eclipse.org/content/repositories/paho-snapshots/"
 >   }
>}
>
>android {
>   compileSdkVersion 26
>    buildToolsVersion "26.0.2"
>    defaultConfig {
>        applicationId "com.e_rahit.e_rachitcloudadsplayer"
>        minSdkVersion 21
>        targetSdkVersion 26
>        versionCode 1
>        versionName "1.0"
>        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
>        manifestPlaceholders = [onesignal_app_id: "32c4c174-2591-4033-b3e2-29e23dd3624a",
>                                // Project number pulled from dashboard, local value is ignored.
>                                onesignal_google_project_number: "REMOTE"]
>    }
>    buildTypes {
>        release {
>            minifyEnabled false
>            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>        }
>    }
>}
>
>dependencies {
>    implementation fileTree(dir: 'libs', include: ['*.jar'])
>    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
>    testImplementation 'junit:junit:4.12'
>    androidTestImplementation('com.android.support.test.espresso:espresso-core:3.0.1', {
>        exclude group: 'com.android.support', module: 'support-annotations'
>    })
>    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
>
>    compile 'com.android.support:appcompat-v7:26.1.0'
>
>    compile 'com.github.bumptech.glide:glide:4.2.0'
>    annotationProcessor 'com.github.bumptech.glide:compiler:4.2.0'
>
>    compile 'com.squareup.retrofit2:retrofit:2.3.0'
>    compile 'com.squareup.retrofit2:converter-gson:2.3.0'
>    compile 'com.squareup.retrofit2:adapter-rxjava:2.3.0'
>    compile 'com.fasterxml.jackson.core:jackson-annotations:2.9.2'
>    compile 'io.reactivex:rxandroid:1.2.1'
>    compile 'com.google.code.gson:gson:2.8.1'
>    compile 'com.squareup.okhttp3:logging-interceptor:3.4.1'
>
>    compile 'com.amazonaws:aws-android-sdk-core:2.6.12'
>    compile 'com.amazonaws:aws-android-sdk-ddb:2.6.5'
>    compile 'com.amazonaws:aws-android-sdk-iot:2.6.5'
>    compile 'com.amazonaws:aws-android-sdk-cognito:2.6.12'
>
>    compile 'com.onesignal:OneSignal:[3.6.5, 3.99.99]'
>
>    compile 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0'
>    compile 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
>    compile 'joda-time:joda-time:2.9.9'
>}

and this is the issue i am getting

> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
	at com.android.builder.dexing.DxDexArchiveMerger.mergeMonoDex(DxDexArchiveMerger.java:177)
	at com.android.builder.dexing.DxDexArchiveMerger.mergeDexArchives(DxDexArchiveMerger.java:118)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:97)
	at com.android.build.gradle.internal.transforms.ExternalLibsMergerTransform.transform(ExternalLibsMergerTransform.kt:121)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:222)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:218)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:213)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 27 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
	at com.android.builder.dexing.DxDexArchiveMerger.lambda$mergeMonoDex$0(DxDexArchiveMerger.java:171)
Caused by: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
Caused by: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:72)
	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Caused by: com.android.dex.DexException: Multiple dex files define Lorg/intellij/lang/annotations/MagicConstant;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
	... 1 more

**Comment by thehecht** [comment]
Same problem here =( too bad... can't fix it... multi dex is enabled and everything else is ok.

**Comment by bmbariah** [comment]
Try this in your app's build.gradle .  Tweak as needed

````java //force all libraries to use version declared...
project.configurations.all {
    resolutionStrategy.eachDependency { details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion rootProject.ext.supportLibraryVersion
            }
        }
    }
}

configurations {
    compile.exclude group: 'org.jetbrains', module: 'annotations'
    compile.exclude module: 'spring-core'
    compile.exclude module: 'spring-web'
    compile.exclude module: 'commons-logging'
}`

**Comment by enrasoft** [comment]
Same here, @bmbariah solution doesn't work for me.

**Comment by dpetrov-appolica** [comment]
Same issue as #11
